In [1]:
import pandas as pd
import numpy as np

In [3]:
serving=pd.read_csv('Serving_Size.csv')
products=pd.read_csv('Products.csv',low_memory=False)
deriv=pd.read_csv('Derivation_Code_Description.csv')
nutrient=pd.read_csv('nutrient.csv', low_memory=False)
upc=pd.read_excel('Grocery_UPC_Database.xlsx')

In [7]:
#productupc=pd.merge(products, upc, left_on='gtin_upc',right_on='upc12',how='left')
productupc.head()

,NDB_Number,long_name,data_source,gtin_upc,manufacturer,date_modified,date_available,ingredients_english,grp_id,upc14,upc12,brand,name
0,45001524,MOCHI ICE CREAM BONBONS,LI,1.902213e+10,"G. T. Japan, Inc.",2017-11-15 19:19:38,2017-11-15 19:19:38,"ICE CREAM INGREDIENTS: MILK, CREAM, SUGAR, STR...",NaN,NaN,NaN,NaN,NaN
1,45001528,CHIPOTLE BARBECUE SAUCE,LI,5.051379e+12,FRESH & EASY,2018-04-26 17:23:31,2018-04-26 17:23:31,"WATER, SUGAR, TOMATO PASTE, MOLASSES, DISTILLE...",NaN,NaN,NaN,NaN,NaN
2,45001529,HOT & SPICY BARBECUE SAUCE,LI,5.051379e+12,FRESH & EASY,2018-04-26 18:17:37,2018-04-26 18:17:37,"SUGAR, WATER, DISTILLED VINEGAR, TOMATO PASTE,...",NaN,NaN,NaN,NaN,NaN
3,45001530,BARBECUE SAUCE,LI,5.051379e+12,FRESH & EASY,2018-04-26 17:24:00,2018-04-26 17:24:00,"TOMATO PUREE (WATER, TOMATO PASTE), SUGAR, DIS...",NaN,NaN,NaN,NaN,NaN
4,45001531,BARBECUE SAUCE,LI,5.051379e+12,FRESH & EASY,2018-04-26 17:47:41,2018-04-26 17:47:41,"SUGAR, DISTILLED VINEGAR, WATER, TOMATO PASTE,...",NaN,NaN,NaN,NaN,NaN

In [5]:
productupc.info(),products.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119546 entries, 0 to 119545
Data columns (total 13 columns):
NDB_Number             119546 non-null object
long_name              119545 non-null object
data_source            119545 non-null object
gtin_upc               119545 non-null float64
manufacturer           119545 non-null object
date_modified          119545 non-null object
date_available         119545 non-null object
ingredients_english    119023 non-null object
grp_id                 17142 non-null float64
upc14                  17142 non-null float64
upc12                  17142 non-null float64
brand                  17142 non-null object
name                   17142 non-null object
dtypes: float64(4), object(9)
memory usage: 12.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119546 entries, 0 to 119545
Data columns (total 8 columns):
NDB_Number             119546 non-null object
long_name              119545 non-null object
data_source            119545 non-null object
gtin_upc               119545 non-null float64
manufacturer           119545 non-null object
date_modified          119545 non-null object
date_available         119545 non-null object
ingredients_english    119023 non-null object
dtypes: float64(1), object(7)
memory usage: 7.3+ MB

(None, None)

In [6]:
nutrient.head()

,NDB_No,Nutrient_Code,Nutrient_name,Derivation_Code,Output_value,Output_uom
0,45127487,203.0,Protein,LCGA,4.3,g
1,45127487,204.0,Total lipid (fat),LCGA,18.9,g
2,45127487,205.0,"Carbohydrate, by difference",LCGA,72.8,g
3,45127487,207.0,Ash,LCGA,2.0,g
4,45127487,255.0,Water,LCGA,2.0,g

In [15]:
proupcnut=pd.merge(productupc,nutrient,right_on='NDB_No',left_on='NDB_Number')
proupcnut.head()
for x in [proupcnut,productupc,nutrient]: print(x.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1101610 entries, 0 to 1101609
Data columns (total 19 columns):
NDB_Number             1101610 non-null object
long_name              1101609 non-null object
data_source            1101609 non-null object
gtin_upc               1101609 non-null float64
manufacturer           1101609 non-null object
date_modified          1101609 non-null object
date_available         1101609 non-null object
ingredients_english    1096960 non-null object
grp_id                 125753 non-null float64
upc14                  125753 non-null float64
upc12                  125753 non-null float64
brand                  125753 non-null object
name                   125753 non-null object
NDB_No                 1101610 non-null object
Nutrient_Code          1101609 non-null float64
Nutrient_name          1101609 non-null object
Derivation_Code        1101609 non-null object
Output_value           1101609 non-null float64
Output_uom             1101609 non-null object
dtypes: float64(6), object(13)
memory usage: 168.1+ MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 119546 entries, 0 to 119545
Data columns (total 13 columns):
NDB_Number             119546 non-null object
long_name              119545 non-null object
data_source            119545 non-null object
gtin_upc               119545 non-null float64
manufacturer           119545 non-null object
date_modified          119545 non-null object
date_available         119545 non-null object
ingredients_english    119023 non-null object
grp_id                 17142 non-null float64
upc14                  17142 non-null float64
upc12                  17142 non-null float64
brand                  17142 non-null object
name                   17142 non-null object
dtypes: float64(4), object(9)
memory usage: 12.8+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615745 entries, 0 to 1615744
Data columns (total 6 columns):
NDB_No             1615745 non-null object
Nutrient_Code      1615744 non-null float64
Nutrient_name      1615744 non-null object
Derivation_Code    1615744 non-null object
Output_value       1615744 non-null float64
Output_uom         1615744 non-null object
dtypes: float64(2), object(4)
memory usage: 74.0+ MB
None

In [16]:
nutrient.head()

,NDB_No,Nutrient_Code,Nutrient_name,Derivation_Code,Output_value,Output_uom
0,45127487,203.0,Protein,LCGA,4.3,g
1,45127487,204.0,Total lipid (fat),LCGA,18.9,g
2,45127487,205.0,"Carbohydrate, by difference",LCGA,72.8,g
3,45127487,207.0,Ash,LCGA,2.0,g
4,45127487,255.0,Water,LCGA,2.0,g

In [27]:
nutrient['allkcal']=4*nutrient['Output_value'][nutrient['Nutrient_name']=='Protein']

In [28]:
nutrient['allkcal']=4*nutrient['Output_value'][nutrient['Nutrient_name']=='Carbohydrate, by difference']

In [29]:
nutrient['allkcal']=9*nutrient['Output_value'][nutrient['Nutrient_name']=='Total lipid (fat)']

In [53]:
energy=nutrient[nutrient['Nutrient_name']=='Energy'].rename(columns=({'Output_value':'kcal'})).drop(['Derivation_Code','Nutrient_name','allkcal','Output_uom'],axis=1)
energy.head() 
#{'oldName1': 'newName1', 'oldName2': 'newName2'}

        NDB_No  Nutrient_Code   kcal
33    45128706          208.0  416.0
3226  45127070          208.0  370.0
3932  45321248          208.0   42.0
3943  45310876          208.0  357.0
3957  45243998          208.0  367.0

In [57]:
carbs=nutrient[nutrient['Nutrient_name']=='Carbohydrate, by difference'].rename(columns=({'Output_value':'carb gram'})).drop(['Derivation_Code','Nutrient_name','allkcal','Output_uom','Nutrient_Code'],axis=1)
print(carbs.head() )
fat=nutrient[nutrient['Nutrient_name']=='Total lipid (fat)'].rename(columns=({'Output_value':'fat gram'})).drop(['Derivation_Code','Nutrient_name','allkcal','Output_uom','Nutrient_Code'],axis=1)
print(fat.head() )
protein=nutrient[nutrient['Nutrient_name']=='Protein'].rename(columns=({'Output_value':'protein gram'})).drop(['Derivation_Code','Nutrient_name','allkcal','Output_uom','Nutrient_Code'],axis=1)
protein.head()

       NDB_No  carb gram
2    45127487       72.8
31   45128706       76.4
63   45129911       77.0
92   45129186        1.0
102  45129160        1.0
       NDB_No  fat gram
1    45127487      18.9
30   45128706       8.5
62   45129911      10.2
91   45129186       8.0
101  45129160       7.0

       NDB_No  protein gram
0    45127487           4.3
29   45128706          10.1
61   45129911           3.0
90   45129186          11.0
100  45129160          12.0

In [60]:
macro=pd.merge(pd.merge(pd.merge(energy,fat,on='NDB_No'),protein,on='NDB_No'),carbs, on='NDB_No')
macro.head()

     NDB_No  Nutrient_Code   kcal  fat gram  protein gram  carb gram
0  45128706          208.0  416.0      8.50         10.10      76.40
1  45127070          208.0  370.0      3.70          5.20      87.80
2  45321248          208.0   42.0      0.00          1.67       8.33
3  45310876          208.0  357.0      3.57          7.14      71.43
4  45243998          208.0  367.0      1.67         13.33      73.33

In [64]:
4*(76.40+10.10)+9*8.50

422.5

In [65]:
	416.0/422.5

0.9846153846153847

In [67]:
len(serving)

118956

In [69]:
serving.NDB_No.nunique()

118956

In [71]:
serving.Serving_Size_UOM.value_counts()

g     109114
ml      9841
Name: Serving_Size_UOM, dtype: int64

In [72]:
serving.head()

,NDB_No,Serving_Size,Serving_Size_UOM,Household_Serving_Size,Household_Serving_Size_UOM,Preparation_State
0,45001524,40.0,g,1.0,PIECE,NaN
1,45001528,37.0,g,2.0,Tbsp,NaN
2,45001529,34.0,g,2.0,Tbsp,NaN
3,45001530,35.0,g,2.0,Tbsp,NaN
4,45001531,37.0,g,2.0,Tbsp,NaN

In [73]:
servingnutr=pd.merge(serving,nutrient,on='NDB_No')
servingnutr.head()

,NDB_No,Serving_Size,Serving_Size_UOM,Household_Serving_Size,Household_Serving_Size_UOM,Preparation_State,Nutrient_Code,Nutrient_name,Derivation_Code,Output_value,Output_uom,allkcal
0,45001581,56.0,g,2.0,ONZ,NaN,203.0,Protein,LCCS,17.86,g,NaN
1,45001581,56.0,g,2.0,ONZ,NaN,204.0,Total lipid (fat),LCCS,4.46,g,40.14
2,45001581,56.0,g,2.0,ONZ,NaN,205.0,"Carbohydrate, by difference",LCCS,3.57,g,NaN
3,45001581,56.0,g,2.0,ONZ,NaN,208.0,Energy,LCCS,125.00,kcal,NaN
4,45001581,56.0,g,2.0,ONZ,NaN,269.0,"Sugars, total",LCCS,3.57,g,NaN

In [74]:
len(servingnutr),len(serving),len(nutrient)

(1099262, 118956, 1615745)

In [75]:
servingnutr['amtserv']=servingnutr['Output_value']/servingnutr['Serving_Size']

In [81]:
servingnutr['nutruniservuni']=servingnutr['Serving_Size_UOM'].map(str)+ servingnutr['Output_uom']
#dataframe["period"] = dataframe["Year"].map(str) + dataframe["quarter"]

In [82]:
servingnutr.head(10)

,NDB_No,Serving_Size,Serving_Size_UOM,Household_Serving_Size,Household_Serving_Size_UOM,Preparation_State,Nutrient_Code,Nutrient_name,Derivation_Code,Output_value,Output_uom,allkcal,amtserv,nutruniservuni
0,45001581,56.0,g,2.0,ONZ,NaN,203.0,Protein,LCCS,17.86,g,NaN,0.318929,gg
1,45001581,56.0,g,2.0,ONZ,NaN,204.0,Total lipid (fat),LCCS,4.46,g,40.14,0.079643,gg
2,45001581,56.0,g,2.0,ONZ,NaN,205.0,"Carbohydrate, by difference",LCCS,3.57,g,NaN,0.063750,gg
3,45001581,56.0,g,2.0,ONZ,NaN,208.0,Energy,LCCS,125.00,kcal,NaN,2.232143,gkcal
4,45001581,56.0,g,2.0,ONZ,NaN,269.0,"Sugars, total",LCCS,3.57,g,NaN,0.063750,gg
5,45001581,56.0,g,2.0,ONZ,NaN,291.0,"Fiber, total dietary",LCCD,0.00,g,NaN,0.000000,gg
6,45001581,56.0,g,2.0,ONZ,NaN,301.0,"Calcium, Ca",LCCD,0.00,mg,NaN,0.000000,gmg
7,45001581,56.0,g,2.0,ONZ,NaN,303.0,"Iron, Fe",LCCD,0.64,mg,NaN,0.011429,gmg
8,45001581,56.0,g,2.0,ONZ,NaN,307.0,"Sodium, Na",LCCS,1161.00,mg,NaN,20.732143,gmg
9,45001581,56.0,g,2.0,ONZ,NaN,318.0,"Vitamin A, IU",LCCD,0.00,IU,NaN,0.000000,gIU

In [88]:
relnutr=servingnutr.groupby(['NDB_No','Nutrient_name','nutruniservuni']).mean().unstack().unstack()

In [89]:
relnutr.head()

               Serving_Size                                              \
nutruniservuni          gIU
Nutrient_name          10:0 12:0 8:0 Alcohol, ethyl Ash Biotin Caffeine
NDB_No
45001581                NaN  NaN NaN            NaN NaN    NaN      NaN
45001582                NaN  NaN NaN            NaN NaN    NaN      NaN
45001591                NaN  NaN NaN            NaN NaN    NaN      NaN
45001595                NaN  NaN NaN            NaN NaN    NaN      NaN
45001596                NaN  NaN NaN            NaN NaN    NaN      NaN

                                                                            \
nutruniservuni
Nutrient_name  Calcium, Ca Carbohydrate, by difference Carbohydrate, other
NDB_No
45001581               NaN                         NaN                 NaN
45001582               NaN                         NaN                 NaN
45001591               NaN                         NaN                 NaN
45001595               NaN                         NaN                 NaN
45001596               NaN                         NaN                 NaN

                 ...         amtserv              \
nutruniservuni   ...            mlmg
Nutrient_name    ...    Vitamin B-12 Vitamin B-6
NDB_No           ...
45001581         ...             NaN         NaN
45001582         ...             NaN         NaN
45001591         ...             NaN         NaN
45001595         ...             NaN         NaN
45001596         ...             NaN         NaN

                                                                   \
nutruniservuni
Nutrient_name  Vitamin C, total ascorbic acid Vitamin D Vitamin E
NDB_No
45001581                                  NaN       NaN       NaN
45001582                                  NaN       NaN       NaN
45001591                                  NaN       NaN       NaN
45001595                                  NaN       NaN       NaN
45001596                                  NaN       NaN       NaN

                                                                            \
nutruniservuni
Nutrient_name  Vitamin E (label entry primarily) Vitamin K (phylloquinone)
NDB_No
45001581                                     NaN                       NaN
45001582                                     NaN                       NaN
45001591                                     NaN                       NaN
45001595                                     NaN                       NaN
45001596                                     NaN                       NaN


nutruniservuni
Nutrient_name  Water Xylitol Zinc, Zn
NDB_No
45001581         NaN     NaN      NaN
45001582         NaN     NaN      NaN
45001591         NaN     NaN      NaN
45001595         NaN     NaN      NaN
45001596         NaN     NaN      NaN

[5 rows x 3894 columns]

In [90]:
prodrelnutr=pd.merge(relnutr,productupc, on='NDB_No')

/Users/meleciawright/anaconda/lib/python3.5/site-packages/pandas/tools/merge.py:205: UserWarning: merging between different levels can give an unintended result (3 levels on the left, 1 on the right)
  warnings.warn(msg, UserWarning)

KeyError: 'NDB_No'

In [ ]:
servingnutr.groupby(['NDB_No','Nutrient_name','nutruniservuni']).mean().unstack().unstack().unstack(.head()

In [86]:
servingnutr.groupby(['NDB_No','Nutrient_name','nutruniservuni']).mean().unstack().unstack()

                                        Serving_Size                         \
nutruniservuni                                   gIU    gg gkcal gmcg   gmg
NDB_No   Nutrient_name
45001581 Calcium, Ca                             NaN   NaN   NaN  NaN  56.0
         Carbohydrate, by difference             NaN  56.0   NaN  NaN   NaN
         Cholesterol                             NaN   NaN   NaN  NaN  56.0
         Energy                                  NaN   NaN  56.0  NaN   NaN
         Fatty acids, total saturated            NaN  56.0   NaN  NaN   NaN
         Fatty acids, total trans                NaN  56.0   NaN  NaN   NaN
         Fiber, total dietary                    NaN  56.0   NaN  NaN   NaN
         Iron, Fe                                NaN   NaN   NaN  NaN  56.0
         Protein                                 NaN  56.0   NaN  NaN   NaN
         Sodium, Na                              NaN   NaN   NaN  NaN  56.0
         Sugars, total                           NaN  56.0   NaN  NaN   NaN
         Total lipid (fat)                       NaN  56.0   NaN  NaN   NaN
         Vitamin A, IU                          56.0   NaN   NaN  NaN   NaN
         Vitamin C, total ascorbic acid          NaN   NaN   NaN  NaN  56.0
45001582 Calcium, Ca                             NaN   NaN   NaN  NaN  56.0
         Carbohydrate, by difference             NaN  56.0   NaN  NaN   NaN
         Cholesterol                             NaN   NaN   NaN  NaN  56.0
         Energy                                  NaN   NaN  56.0  NaN   NaN
         Fatty acids, total saturated            NaN  56.0   NaN  NaN   NaN
         Fatty acids, total trans                NaN  56.0   NaN  NaN   NaN
         Fiber, total dietary                    NaN  56.0   NaN  NaN   NaN
         Iron, Fe                                NaN   NaN   NaN  NaN  56.0
         Protein                                 NaN  56.0   NaN  NaN   NaN
         Sodium, Na                              NaN   NaN   NaN  NaN  56.0
         Sugars, total                           NaN  56.0   NaN  NaN   NaN
         Total lipid (fat)                       NaN  56.0   NaN  NaN   NaN
         Vitamin A, IU                          56.0   NaN   NaN  NaN   NaN
         Vitamin C, total ascorbic acid          NaN   NaN   NaN  NaN  56.0
45001591 Calcium, Ca                             NaN   NaN   NaN  NaN  28.0
         Carbohydrate, by difference             NaN  28.0   NaN  NaN   NaN
...                                              ...   ...   ...  ...   ...
45209489 Vitamin A, IU                          32.0   NaN   NaN  NaN   NaN
         Vitamin C, total ascorbic acid          NaN   NaN   NaN  NaN  32.0
45209493 Calcium, Ca                             NaN   NaN   NaN  NaN  54.0
         Carbohydrate, by difference             NaN  54.0   NaN  NaN   NaN
         Cholesterol                             NaN   NaN   NaN  NaN  54.0
         Energy                                  NaN   NaN  54.0  NaN   NaN
         Fatty acids, total saturated            NaN  54.0   NaN  NaN   NaN
         Fatty acids, total trans                NaN  54.0   NaN  NaN   NaN
         Fiber, total dietary                    NaN  54.0   NaN  NaN   NaN
         Iron, Fe                                NaN   NaN   NaN  NaN  54.0
         Protein                                 NaN  54.0   NaN  NaN   NaN
         Sodium, Na                              NaN   NaN   NaN  NaN  54.0
         Sugars, total                           NaN  54.0   NaN  NaN   NaN
         Total lipid (fat)                       NaN  54.0   NaN  NaN   NaN
         Vitamin A, IU                          54.0   NaN   NaN  NaN   NaN
         Vitamin C, total ascorbic acid          NaN   NaN   NaN  NaN  54.0
45209495 Calcium, Ca                             NaN   NaN   NaN  NaN  40.0
         Carbohydrate, by difference             NaN  40.0   NaN  NaN   NaN
         Cholesterol                             NaN   NaN   NaN  NaN  40.0
         Energy                                  NaN   NaN  40.0  NaN   NaN
         Fatty acids, total saturated            NaN  40.0   NaN  NaN   NaN
         Fatty acids, total trans                NaN  40.0   NaN  NaN   NaN
         Fiber, total dietary                    NaN  40.0   NaN  NaN   NaN
         Iron, Fe                                NaN   NaN   NaN  NaN  40.0
         Protein                                 NaN  40.0   NaN  NaN   NaN
         Sodium, Na                              NaN   NaN   NaN  NaN  40.0
         Sugars, total                           NaN  40.0   NaN  NaN   NaN
         Total lipid (fat)                       NaN  40.0   NaN  NaN   NaN
         Vitamin A, IU                          40.0   NaN   NaN  NaN   NaN
         Vitamin C, total ascorbic acid          NaN   NaN   NaN  NaN  40.0

                                                                      ...   \
nutruniservuni                          gmg_ATE mlIU mlg mlkcal mlmcg ...
NDB_No   Nutrient_name                                                ...
45001581 Calcium, Ca                        NaN  NaN NaN    NaN   NaN ...
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN ...
         Cholesterol                        NaN  NaN NaN    NaN   NaN ...
         Energy                             NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN ...
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN ...
         Iron, Fe                           NaN  NaN NaN    NaN   NaN ...
         Protein                            NaN  NaN NaN    NaN   NaN ...
         Sodium, Na                         NaN  NaN NaN    NaN   NaN ...
         Sugars, total                      NaN  NaN NaN    NaN   NaN ...
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN ...
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN ...
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN ...
45001582 Calcium, Ca                        NaN  NaN NaN    NaN   NaN ...
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN ...
         Cholesterol                        NaN  NaN NaN    NaN   NaN ...
         Energy                             NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN ...
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN ...
         Iron, Fe                           NaN  NaN NaN    NaN   NaN ...
         Protein                            NaN  NaN NaN    NaN   NaN ...
         Sodium, Na                         NaN  NaN NaN    NaN   NaN ...
         Sugars, total                      NaN  NaN NaN    NaN   NaN ...
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN ...
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN ...
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN ...
45001591 Calcium, Ca                        NaN  NaN NaN    NaN   NaN ...
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN ...
...                                         ...  ...  ..    ...   ... ...
45209489 Vitamin A, IU                      NaN  NaN NaN    NaN   NaN ...
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN ...
45209493 Calcium, Ca                        NaN  NaN NaN    NaN   NaN ...
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN ...
         Cholesterol                        NaN  NaN NaN    NaN   NaN ...
         Energy                             NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN ...
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN ...
         Iron, Fe                           NaN  NaN NaN    NaN   NaN ...
         Protein                            NaN  NaN NaN    NaN   NaN ...
         Sodium, Na                         NaN  NaN NaN    NaN   NaN ...
         Sugars, total                      NaN  NaN NaN    NaN   NaN ...
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN ...
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN ...
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN ...
45209495 Calcium, Ca                        NaN  NaN NaN    NaN   NaN ...
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN ...
         Cholesterol                        NaN  NaN NaN    NaN   NaN ...
         Energy                             NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN ...
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN ...
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN ...
         Iron, Fe                           NaN  NaN NaN    NaN   NaN ...
         Protein                            NaN  NaN NaN    NaN   NaN ...
         Sodium, Na                         NaN  NaN NaN    NaN   NaN ...
         Sugars, total                      NaN  NaN NaN    NaN   NaN ...
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN ...
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN ...
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN ...

                                          amtserv                             \
nutruniservuni                                 gg      gkcal gmcg        gmg
NDB_No   Nutrient_name
45001581 Calcium, Ca                          NaN        NaN  NaN   0.000000
         Carbohydrate, by difference     0.063750        NaN  NaN        NaN
         Cholesterol                          NaN        NaN  NaN   0.964286
         Energy                               NaN   2.232143  NaN        NaN
         Fatty acids, total saturated    0.031964        NaN  NaN        NaN
         Fatty acids, total trans        0.000000        NaN  NaN        NaN
         Fiber, total dietary            0.000000        NaN  NaN        NaN
         Iron, Fe                             NaN        NaN  NaN   0.011429
         Protein                         0.318929        NaN  NaN        NaN
         Sodium, Na                           NaN        NaN  NaN  20.732143
         Sugars, total                   0.063750        NaN  NaN        NaN
         Total lipid (fat)               0.079643        NaN  NaN        NaN
         Vitamin A, IU                        NaN        NaN  NaN        NaN
         Vitamin C, total ascorbic acid       NaN        NaN  NaN   0.000000
45001582 Calcium, Ca                          NaN        NaN  NaN   0.000000
         Carbohydrate, by difference     0.031964        NaN  NaN        NaN
         Cholesterol                          NaN        NaN  NaN   0.964286
         Energy                               NaN   3.196429  NaN        NaN
         Fatty acids, total saturated    0.047857        NaN  NaN        NaN
         Fatty acids, total trans        0.000000        NaN  NaN        NaN
         Fiber, total dietary            0.000000        NaN  NaN        NaN
         Iron, Fe                             NaN        NaN  NaN   0.034464
         Protein                         0.382679        NaN  NaN        NaN
         Sodium, Na                           NaN        NaN  NaN  19.125000
         Sugars, total                   0.031964        NaN  NaN        NaN
         Total lipid (fat)               0.143571        NaN  NaN        NaN
         Vitamin A, IU                        NaN        NaN  NaN        NaN
         Vitamin C, total ascorbic acid       NaN        NaN  NaN   0.000000
45001591 Calcium, Ca                          NaN        NaN  NaN   0.000000
         Carbohydrate, by difference     0.765357        NaN  NaN        NaN
...                                           ...        ...  ...        ...
45209489 Vitamin A, IU                        NaN        NaN  NaN        NaN
         Vitamin C, total ascorbic acid       NaN        NaN  NaN   0.000000
45209493 Calcium, Ca                          NaN        NaN  NaN   0.685185
         Carbohydrate, by difference     1.028889        NaN  NaN        NaN
         Cholesterol                          NaN        NaN  NaN   1.203704
         Energy                               NaN   6.166667  NaN        NaN
         Fatty acids, total saturated    0.068519        NaN  NaN        NaN
         Fatty acids, total trans        0.000000        NaN  NaN        NaN
         Fiber, total dietary            0.068519        NaN  NaN        NaN
         Iron, Fe                             NaN        NaN  NaN   0.024630
         Protein                         0.068519        NaN  NaN        NaN
         Sodium, Na                           NaN        NaN  NaN   4.796296
         Sugars, total                   0.822963        NaN  NaN        NaN
         Total lipid (fat)               0.205741        NaN  NaN        NaN
         Vitamin A, IU                        NaN        NaN  NaN        NaN
         Vitamin C, total ascorbic acid       NaN        NaN  NaN   0.081481
45209495 Calcium, Ca                          NaN        NaN  NaN   1.250000
         Carbohydrate, by difference     1.625000        NaN  NaN        NaN
         Cholesterol                          NaN        NaN  NaN   0.000000
         Energy                               NaN  11.875000  NaN        NaN
         Fatty acids, total saturated    0.500000        NaN  NaN        NaN
         Fatty acids, total trans        0.000000        NaN  NaN        NaN
         Fiber, total dietary            0.062500        NaN  NaN        NaN
         Iron, Fe                             NaN        NaN  NaN   0.022500
         Protein                         0.062500        NaN  NaN        NaN
         Sodium, Na                           NaN        NaN  NaN   0.625000
         Sugars, total                   1.437500        NaN  NaN        NaN
         Total lipid (fat)               0.625000        NaN  NaN        NaN
         Vitamin A, IU                        NaN        NaN  NaN        NaN
         Vitamin C, total ascorbic acid       NaN        NaN  NaN   0.000000


nutruniservuni                          gmg_ATE mlIU mlg mlkcal mlmcg mlmg
NDB_No   Nutrient_name
45001581 Calcium, Ca                        NaN  NaN NaN    NaN   NaN  NaN
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN  NaN
         Cholesterol                        NaN  NaN NaN    NaN   NaN  NaN
         Energy                             NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN  NaN
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN  NaN
         Iron, Fe                           NaN  NaN NaN    NaN   NaN  NaN
         Protein                            NaN  NaN NaN    NaN   NaN  NaN
         Sodium, Na                         NaN  NaN NaN    NaN   NaN  NaN
         Sugars, total                      NaN  NaN NaN    NaN   NaN  NaN
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN  NaN
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN  NaN
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN  NaN
45001582 Calcium, Ca                        NaN  NaN NaN    NaN   NaN  NaN
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN  NaN
         Cholesterol                        NaN  NaN NaN    NaN   NaN  NaN
         Energy                             NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN  NaN
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN  NaN
         Iron, Fe                           NaN  NaN NaN    NaN   NaN  NaN
         Protein                            NaN  NaN NaN    NaN   NaN  NaN
         Sodium, Na                         NaN  NaN NaN    NaN   NaN  NaN
         Sugars, total                      NaN  NaN NaN    NaN   NaN  NaN
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN  NaN
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN  NaN
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN  NaN
45001591 Calcium, Ca                        NaN  NaN NaN    NaN   NaN  NaN
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN  NaN
...                                         ...  ...  ..    ...   ...  ...
45209489 Vitamin A, IU                      NaN  NaN NaN    NaN   NaN  NaN
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN  NaN
45209493 Calcium, Ca                        NaN  NaN NaN    NaN   NaN  NaN
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN  NaN
         Cholesterol                        NaN  NaN NaN    NaN   NaN  NaN
         Energy                             NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN  NaN
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN  NaN
         Iron, Fe                           NaN  NaN NaN    NaN   NaN  NaN
         Protein                            NaN  NaN NaN    NaN   NaN  NaN
         Sodium, Na                         NaN  NaN NaN    NaN   NaN  NaN
         Sugars, total                      NaN  NaN NaN    NaN   NaN  NaN
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN  NaN
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN  NaN
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN  NaN
45209495 Calcium, Ca                        NaN  NaN NaN    NaN   NaN  NaN
         Carbohydrate, by difference        NaN  NaN NaN    NaN   NaN  NaN
         Cholesterol                        NaN  NaN NaN    NaN   NaN  NaN
         Energy                             NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total saturated       NaN  NaN NaN    NaN   NaN  NaN
         Fatty acids, total trans           NaN  NaN NaN    NaN   NaN  NaN
         Fiber, total dietary               NaN  NaN NaN    NaN   NaN  NaN
         Iron, Fe                           NaN  NaN NaN    NaN   NaN  NaN
         Protein                            NaN  NaN NaN    NaN   NaN  NaN
         Sodium, Na                         NaN  NaN NaN    NaN   NaN  NaN
         Sugars, total                      NaN  NaN NaN    NaN   NaN  NaN
         Total lipid (fat)                  NaN  NaN NaN    NaN   NaN  NaN
         Vitamin A, IU                      NaN  NaN NaN    NaN   NaN  NaN
         Vitamin C, total ascorbic acid     NaN  NaN NaN    NaN   NaN  NaN

[1099258 rows x 66 columns]

In [77]:
pd.crosstab()

Output_uom           IU       g   kcal   mcg      mg  mg_ATE
Serving_Size_UOM
g                 66205  514628  73073  6022  369296       4
ml                 3403   36834   6904   494   22398       0

In [80]:
pd.concat(servingnutr.iloc[0].Serving_Size_UOM,servingnutr.iloc[0].Output_uom)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "str"

In [79]:
servingnutr.iloc[0].Serving_Size_UOM

'g'

In [66]:
(4*(5.20+87.80)+9*3.70)/370

1.0954054054054054

       NDB_No  Nutrient_Code  fat gram
1    45127487          204.0      18.9
30   45128706          204.0       8.5
62   45129911          204.0      10.2
91   45129186          204.0       8.0
101  45129160          204.0       7.0

       NDB_No  Nutrient_Code  protein gram
0    45127487          203.0           4.3
29   45128706          203.0          10.1
61   45129911          203.0           3.0
90   45129186          203.0          11.0
100  45129160          203.0          12.0

In [54]:
nutrient.Nutrient_name.value_counts()

Carbohydrate, by difference           120004
Total lipid (fat)                     119988
Protein                               119905
Sodium, Na                            119577
Energy                                118295
Sugars, total                         112115
Fatty acids, total saturated          102363
Cholesterol                           100903
Fiber, total dietary                   98304
Iron, Fe                               97499
Calcium, Ca                            97093
Fatty acids, total trans               96333
Vitamin C, total ascorbic acid         93835
Vitamin A, IU                          92033
Potassium, K                           20277
Fatty acids, total monounsaturated     15901
Fatty acids, total polyunsaturated     15899
Niacin                                  8152
Thiamin                                 8061
Riboflavin                              8002
Vitamin D                               7910
Vitamin B-6                             5368
Phosphorus, P                           4635
Magnesium, Mg                           4316
Vitamin B-12                            4140
Zinc, Zn                                3648
Folate, total                           3543
Sugars, added                           2376
Fiber, soluble                          2233
Fiber, insoluble                        2095
                                       ...
Taurine                                    4
Starch                                     3
10:0                                       3
Chlorine, Cl                               3
8:0                                        3
Inulin                                     3
Choline, total                             2
Serine                                     1
Glycine                                    1
Tyrosine                                   1
Alanine                                    1
Threonine                                  1
Vitamin D3 (cholecalciferol)               1
Proline                                    1
Cysteine                                   1
Epigallocatechin-3-gallate                 1
Lysine                                     1
Alcohol, ethyl                             1
Arginine                                   1
Phenylalanine                              1
Tryptophan                                 1
Fructose                                   1
Leucine                                    1
Valine                                     1
Methionine                                 1
Isoleucine                                 1
Histidine                                  1
18:3 n-3 c,c,c (ALA)                       1
Glutamic acid                              1
Aspartic acid                              1
Name: Nutrient_name, dtype: int64

In [ ]:
# for now restricting to

In [ ]:
df.pivot(index='Salesman',columns='idx')[['product','price']]

In [25]:
nutrient.drop('Output_uom').pivot('NDB_No','Nutrient_name','Output_value')

ValueError: labels ['Output_uom'] not contained in axis

In [52]:
usdabrand=productupc.brand.value_counts().index
usdabrand[:5]
usdabrand=pd.Series(usdabrand)

Index(['Ahold', 'Goya', 'Del Monte', 'Mccormick', 'Roland'], dtype='object')

In [60]:
amb=pd.read_csv('amb.csv').reset_index() 
amb=amb.ix[:,2]
type(amb)

In [65]:
productupc.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 119546 entries, 0 to 119545
Data columns (total 13 columns):
NDB_Number             119546 non-null object
long_name              119545 non-null object
data_source            119545 non-null object
gtin_upc               119545 non-null float64
manufacturer           119545 non-null object
date_modified          119545 non-null object
date_available         119545 non-null object
ingredients_english    119023 non-null object
grp_id                 17142 non-null float64
upc14                  17142 non-null float64
upc12                  17142 non-null float64
brand                  17142 non-null object
name                   17142 non-null object
dtypes: float64(4), object(9)
memory usage: 12.8+ MB

In [67]:
productupc.name.value_counts()

Pepper Chipotle                                                                      6
Oil Olive Xvrgn                                                                      6
Bean Black                                                                           6
Pepper Jalapeno Sliced                                                               6
Hellmann's Real Mayonnaise                                                           5
Salsa Hot                                                                            5
Diamond Shelled Walnuts                                                              5
Sauce Hot                                                                            5
Kellogg's Raisin Bran Cereal                                                         4
Ferrero Rocher Fine Hazelnut Chocolates                                              4
Bean Pinto                                                                           4
Pepper Red Rstd                                                                      4
Pasta Spaghetti                                                                      4
B&m Original Baked Beans                                                             4
Chef Boyardee Beefaroni                                                              4
Sauerkraut                                                                           4
Pepper Jalapeno Whole                                                                4
Pepper Jalpno Slcd                                                                   4
Salsa Verde                                                                          4
Pom Wonderful 100% Pomegranate Juice                                                 4
Pepper Serrano                                                                       4
Sweet Baby Ray's Barbecue Sauce                                                      4
Breadcrumb Plain                                                                     4
Tomato Crushed                                                                       4
Chef Boyardee Beef Ravioli                                                           4
Ssnng Poultry                                                                        4
Riceland Extra Long Grain Rice                                                       3
Bean Kidney Red                                                                      3
Ocean Spray Cranberry Juice Cocktail From Concentrate                                3
Dinty Moore Hearty Meals Beef Stew                                                   3
                                                                                    ..
Maple Leaf Duck Breast Filet                                                         1
Pepper Mix Giardiniera Ho                                                            1
Bun Sprtd 7grn Hotdog                                                                1
Choc Yrgt Crvrd Almd Strw                                                            1
Mix Ssnng Chinese Bbq                                                                1
Soda 6pk Diet Blk Chry                                                               1
Bertolli Complete Skillet Meal For Two Chicken Marsala & Roasted Redskin Potatoes    1
Mix Bread Irish Btrmlk Ra                                                            1
Barilla Plus Elbows Pasta Multigrain                                                 1
Vinegar Cocount Chili Gng                                                            1
Lea & Perrins Worcestershire Sauce Original All Natural                              1
Sunridge Farms Confections All Natural Dark Chocolate Coconut Chews                  1
Sunbelt Bakery Granola Bars Peanut Butter Chip - 10 Ct                               1
Bar Gf Drk Choc Pppprmnt                                                             1
Mrs. Dash Marinade Salt-free Lime Garlic                                             1
Ahold Beans Cannellini                                                               1
Dell'alpe Instant Polenta                                                            1
Luna Whole Nutrition Bar For Women Nutz Over Chocolate - 6 Ct                        1
Bob's Red Mill Buckwheat Pancake & Waffle Whole Grain Mix                            1
Barilla Tomato & Basil Sauce                                                         1
Health Valley Organic Soup Minestrone No Salt Added                                  1
Sauerkraut Beet & Cabbage                                                            1
Moore's Buffalo Wing Sauce Gluten Free                                               1
Hummus & Quna Chip Rstd G                                                            1
Lasagna Gf Df Chse                                                                   1
Honey Pure Org                                                                       1
Hanover Baked Beans Country Style                                                    1
Prince Thin Spaghetti Pasta                                                          1
Cheese Vlaskaas                                                                      1
Braswell's All Natural Dressing Balsamic Herb Vinaigrette                            1
Name: name, dtype: int64

In [69]:
productupc.name.isnull().sum()

102404

In [70]:
productupc.name.describe()

count               17142
unique              16468
top       Pepper Chipotle
freq                    6
Name: name, dtype: object

In [71]:
'ice cream','juice','soda','yogurt','tomato sauce','chocolate','ketchup','nut','salsa','apple sauce','sauce',
'cookies','jerky','beans','protein bar','apricots','kimchi','cereal','granola',''
productupc.long_name.value_counts()

ICE CREAM                                                                                                      532
PREMIUM ICE CREAM                                                                                              258
SODA                                                                                                           247
POTATO CHIPS                                                                                                   237
CEREAL                                                                                                         158
SALSA                                                                                                          153
PASTA SAUCE                                                                                                    149
APPLE SAUCE                                                                                                    109
100% JUICE                                                                                                     101
GREEK NONFAT YOGURT                                                                                             98
SAUCE                                                                                                           94
TOMATO SAUCE                                                                                                    92
COOKIES                                                                                                         92
BEEF JERKY                                                                                                      91
MILK CHOCOLATE                                                                                                  88
SPARKLING WATER                                                                                                 87
NONFAT YOGURT                                                                                                   85
BBQ SAUCE                                                                                                       85
LOWFAT YOGURT                                                                                                   85
TOMATO KETCHUP                                                                                                  83
PINTO BEANS                                                                                                     78
CANDY                                                                                                           78
COFFEE CREAMER                                                                                                  77
GRANOLA                                                                                                         76
DARK CHOCOLATE                                                                                                  75
DICED TOMATOES                                                                                                  75
CUT GREEN BEANS                                                                                                 74
BLACK BEANS                                                                                                     74
GREEK YOGURT                                                                                                    74
PROTEIN BAR                                                                                                     72
                                                                                                              ...
JELLY BELLY, SMOOTHIE BLEND                                                                                      1
HEALTHY CHOICE Simply Steamers Asian Kung Pao Chicken                                                            1
DARK CHOCOLATE CHERRY CASHEW + ANTIOXIDANTS* BARS                                                                1
WHOLE GRAIN QUICK COOKING OATS                                                                                   1
GOODLIVIN', LEMON CREME COOKIES                                                                                  1
SHARP CHEDDAR STYLE                                                                                              1
RESTAURANT STYLE BACON                                                                                           1
SUNSHINE KRISPY SALTINES .4OZ                                                                                    1
ON-COR, CHICKEN PATTIES                                                                                          1
LAND O LAKES, COCOA SUPREME, HOT COCOA MIX                                                                       1
GRACE, SOYA SAUCE                                                                                                1
GLUTEN-FREE CRUST WITH TOMATO SAUCE, CHICKEN, FIRE ROASTED PEPPERS AND SMOKED PROVOLONE CHEESE                   1
WHOLE FOODS MARKET, DRIED APRICOTS                                                                               1
NATURALLY PROBIOTIC KIMCHI                                                                                       1
IN THE MIX, GOURMET BROWNIE MIX, SALTED CARAMEL                                                                  1
MILK & WHITE CHOCOLATE BALLS                                                                                     1
SLICED HEARTS OF PALM SALAD CUT                                                                                  1
ANGELENO'S, PUEBLO CHIPS                                                                                         1
TRADER JOE'S, HONEY ROASTED COCOA & CHILI PEANUTS & ALMONDS WITH ROASTED SALTED PECANS, SWEET, HOT & SAVORY      1
TRADITIONAL PASSATA                                                                                              1
TAI PEI, MINI VEGETABLE SPRING ROLLS                                                                             1
SEVERINO, SHELLS CHEESE - STUFFED WITH MARINARA                                                                  1
ROUNDY'S SELECT, DECAFFEINATED GREEN TEA                                                                         1
100% NATURAL TOMATO, GARLIC & ONION PASTA SAUCE                                                                  1
POTATO CROWNS                                                                                                    1
NON PAREILS DALLIES                                                                                              1
POP WEAVER, MICROWAVE POPCORN, SRIRACHA                                                                          1
YELLOW CURRY RICE                                                                                                1
IMPORTED SHREDDED GRUYERE CHEESE                                                                                 1
DAVID SEEDS Pumpkin                                                                                              1
Name: long_name, dtype: int64

In [ ]:
#productupc.long_name.value_counts()

In [72]:
productupc.long_name.notnull().sum()

119545

In [73]:
len(productupc)

119546

In [33]:
q=productupc[productupc['gtin_upc'].notnull()]
q['upc12'].describe()

/Users/meleciawright/anaconda/lib/python3.5/site-packages/numpy/lib/function_base.py:3834: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)

count    1.714200e+04
mean     2.675698e+11
std      3.313288e+11
min      9.349503e+07
25%               NaN
50%               NaN
75%               NaN
max      8.999040e+11
Name: upc12, dtype: float64

In [9]:
type(upc.upc12[0] )

numpy.int64

In [10]:
products.NDB_Number.nunique()#119546

119546

In [11]:
products.manufacturer.nunique()

13604

In [14]:
groclist=pd.DataFrame(products.manufacturer.value_counts().index,columns=['usdabrands'])
groclist.head()

              usdabrands
0         The Kroger Co.
1           Meijer, Inc.
2  Wal-Mart Stores, Inc.
3         Conagra Brands
4     Weis Markets, Inc.

In [15]:
groclist

                            usdabrands
0                       The Kroger Co.
1                         Meijer, Inc.
2                Wal-Mart Stores, Inc.
3                       Conagra Brands
4                   Weis Markets, Inc.
5               Topco Associates, Inc.
6                        Target Stores
7                        Safeway, Inc.
8                Food Town Stores Inc.
9                   Kellogg Company US
10                             SPARTAN
11                  Harris-Teeter Inc.
12                     Supervalu, Inc.
13           Wakefern Food Corporation
14                            ROUNDY'S
15            Whole Foods Market, Inc.
16                     Ahold USA, Inc.
17                        Hy-Vee, Inc.
18            Pinnacle Foods Group LLC
19                 Hannaford Bros. Co.
20                   Giant Eagle, Inc.
21        The Moran Group Incorporated
22               Schnuck Markets, Inc.
23          Wegmans Food Markets, Inc.
24           McCormick & Company, Inc.
25      The Hain Celestial Group, Inc.
26                     Ahold Usa, Inc.
27                    Goya Foods, Inc.
28                Del Monte Foods Inc.
29          Western Family Foods, Inc.
...                                ...
13574              Marx Brothers, Inc.
13575         Eliza's Quest Foods, LLC
13576              GABRIELLA'S KITCHEN
13577          Chlorophyll Brands, LLC
13578                Gourmet Epic Inc.
13579             Avitae Holdings, LLC
13580                     ANZIO & SONS
13581                          CECCATE
13582            Hygloss Products Inc.
13583             BRIGITTE'S NATURALLY
13584                       SAM'S WEST
13585          Hollandia Nursery, Inc.
13586                FRESH FROM MEIJER
13587               Vintage Food Corp.
13588            PANTAINORASINGH BRAND
13589                   LEWIS BAKERIES
13590  Gladder's Gourmet Cookies, Inc.
13591  Liquid Management Partners, LLC
13592     Vegas Valley Brewing Company
13593                       DE MI PAIS
13594               Macro-Organic Inc.
13595                          MAAMOUL
13596                      Arriba, LLC
13597                           LUV YU
13598                      STATER BROS
13599                             CHE!
13600                  NAUGHTY OR NICE
13601                  BF Imports Inc.
13602               Fratelli Polli Spa
13603                 Crook-Miller Co.

[13604 rows x 1 columns]

  derivation_code                                Derivation_Descript
0            LCCD  Calculated from a daily value percentage per s...
1            LCCS     Calculated from value per serving size measure
2            LCGA  Given by information provider as an 'approxima...
3            LCGE  Given by information provider as an 'exact' va...
4            LCGL  Given by information provider as a 'less than'...

,NDB_No,Nutrient_Code,Nutrient_name,Derivation_Code,Output_value,Output_uom
0,45127487,203.0,Protein,LCGA,4.3,g
1,45127487,204.0,Total lipid (fat),LCGA,18.9,g
2,45127487,205.0,"Carbohydrate, by difference",LCGA,72.8,g
3,45127487,207.0,Ash,LCGA,2.0,g
4,45127487,255.0,Water,LCGA,2.0,g